LOAD DATA
CHARACTERSET RU8PC866
INTO TABLE umc_payment_files
APPEND
WHEN (5)='Ä' AND (6)='Î' AND (7)='Ä'
(
FILE_ID CONSTANT 1,
ENTDATE SYSDATE,
GL_CODE CONSTANT '2152010'
)
INTO TABLE umc_customer_payments
APPEND
WHEN (5)='|' AND (31)!='Ò'
(
FILE_ID CONSTANT 1,
LINE_NUM POSITION(02:04) INTEGER EXTERNAL,
PHONE_NUMBER POSITION(30:38) "REPLACE( :phone_number, '-', '')",
CUSTCODE POSITION(40:59) CHAR TERMINATED BY WHITESPACE,
AMOUNT POSITION(61:70) "TO_NUMBER(:amount, '99999.99')"
)