LOAD DATA
INTO TABLE umc_payment_files
APPEND
WHEN (5)='Ä' AND (6)='Î' AND (7)='Ä'
TRAILING NULLCOLS
(
FILE_ID SEQUENCE(MAX, 1),
ENTDATE SYSDATE,
GL_CODE CONSTANT '2032010'
)
INTO TABLE umc_customer_payments
APPEND
WHEN (5)='|' AND (30)!=' '
(
FILE_ID CONSTANT 1,
LINE_NUM POSITION(02:04) INTEGER EXTERNAL,
PHONE_NUMBER POSITION(30:38) "REPLACE( :phone_number, '-', '')",
CUSTCODE POSITION(40:59) CHAR,
AMOUNT POSITION(61:70) "TO_NUMBER(:amount, '99999.99')"
)