LOAD DATA
INTO TABLE umc_payment_files
APPEND
WHEN (5)='Ä' AND (6)='Î' AND (7)='Ä'
TRAILING NULLCOLS
(
FILE_ID SEQUENCE(MAX, 1),
ENTDATE SYSDATE,
GL_CODE CONSTANT '2132010'
)
INTO TABLE umc_customer_payments
APPEND
WHEN (9)='|' AND (33)!='T'
(
FILE_ID CONSTANT 1,
LINE_NUM POSITION(06:08) INTEGER EXTERNAL,
PHONE_NUMBER POSITION(31:39) "REPLACE( :phone_number, '-', '')",
CUSTCODE POSITION(42:50) CHAR TERMINATED BY WHITESPACE,
AMOUNT POSITION(60:66) "TO_NUMBER(:amount, '99999.99')"
)